dadrus/heimdall

internal/pipeline/authenticators/jwt_authenticator.go
internal/pipeline/authenticators/jwt_authenticator_test.go
internal/pipeline/authenticators/oauth2_introspection_authenticator.go
internal/pipeline/authenticators/oauth2_introspection_authenticator_test.go

fix: not extracting tokens from cookies by default any more

---

.github/workflows/ci.yml
docker/Dockerfile
docker/debug.Dockerfile

chore: Hadolint support

---

docs/config.yaml
docs/content/docs/configuration/rules/_index.adoc
docs/content/docs/guides/traefik.adoc
docs/content/docs/introduction/about.adoc
docs/content/docs/introduction/architecture.adoc
docs/content/docs/introduction/install.adoc
docs/content/docs/introduction/quickstart.adoc
docs/themes/mytheme/assets/sass/styles.scss

docs: introductionary document

---

docs/content/docs/configuration/pipeline/_index.adoc
docs/content/docs/configuration/pipeline/authorizers.adoc
docs/content/docs/configuration/pipeline/hydrators.adoc
docs/content/docs/configuration/pipeline/mutators.adoc
docs/content/docs/configuration/reference/configuration.adoc
docs/content/docs/guides/traefik.adoc
internal/pipeline/authorizers/config_decoder.go
internal/pipeline/authorizers/local_authorizer.go
internal/pipeline/authorizers/local_authorizer_test.go
internal/pipeline/authorizers/remote_authorizer.go
internal/pipeline/authorizers/remote_authorizer_test.go
internal/pipeline/hydrators/config_decoder.go
internal/pipeline/hydrators/generic_hydrator.go
internal/pipeline/hydrators/generic_hydrator_test.go
internal/pipeline/mutators/config_decoder.go
internal/pipeline/mutators/cookie_mutator_test.go
internal/pipeline/mutators/header_mutator_test.go
internal/pipeline/mutators/jwt_mutator.go
internal/pipeline/mutators/jwt_mutator_test.go
internal/pipeline/script/mapstructure_decoder.go
internal/pipeline/script/script.go
internal/pipeline/script/script_test.go
internal/pipeline/template/mapstructure_decoder.go
internal/pipeline/template/template.go
internal/pipeline/template/template_test.go

feat: Enables usage of heimdall context in specific templates and made template and script compiling on load and not on execute

---

docs/content/docs/getting_started/configuration_introduction.adoc

docs: description on how heimdall can be configured in general

---

internal/config/test_data/test_config.yaml
schema/config.schema.json

fix: trusted_proxy support added to the schema file to allow the validation of the corresponding property

---

internal/pipeline/authenticators/basic_auth_authenticator.go
internal/pipeline/authenticators/basic_auth_authenticator_test.go

fix: basic_auth authenticator is not responsible for the request anymore if the Authorization header does not contain Basic Auth schema

---

docs/content/docs/configuration/reference/configuration.adoc

docs: Management service reference config added

---

docs/content/docs/configuration/pipeline/authorizers.adoc
docs/content/docs/configuration/pipeline/overview.adoc
docs/content/docs/configuration/reference/configuration.adoc
internal/pipeline/authorizers/local_authorizer.go
internal/pipeline/authorizers/remote_authorizer.go
internal/pipeline/authorizers/remote_authorizer_test.go
internal/pipeline/script/script.go
internal/pipeline/script/script_test.go
schema/config.schema.json

feat: Remote authorizer optionally supports verification of responses from the remote system via a script

---

docs/content/docs/configuration/services/decision_api.adoc
docs/content/docs/guides/nginx.adoc

docs: NGINX integration guide

---

internal/config/test_data/test_config.yaml
internal/config/validator_test.go
schema/config.schema.json

fix: Schema fixed to allow TLS key & cert as well as CORS max_age configuration

---

DockerHub-README.md
cmd/serve.go
cmd/serve/decision.go
cmd/serve/proxy.go
docs/content/docs/api/_index.adoc
docs/content/docs/configuration/reference/configuration.adoc
docs/content/docs/configuration/services/configuration_types.adoc
docs/content/docs/configuration/services/decision_api.adoc
docs/content/docs/getting_started/concepts.adoc
docs/content/docs/getting_started/decision_api_quickstart.adoc
docs/content/docs/getting_started/proxy_quickstart.adoc
docs/content/docs/guides/nginx.adoc
docs/content/docs/guides/traefik.adoc
docs/content/docs/operations/cli.adoc
internal/config/default_configuration.go
internal/config/serve.go
internal/config/test_data/test_config.yaml
internal/handler/decision/handler.go
internal/handler/decision/module.go
internal/handler/management/handler.go
internal/handler/management/module.go
internal/handler/prometheus/module.go
internal/handler/proxy/handler.go
internal/handler/proxy/module.go
schema/config.schema.json
test_config.yaml

refactor!: "serve api" command renamed to "serve decision" (incl. wording in docs and logs)

---

DockerHub-README.md

docs: DockerHub README updated to include the usage of proxy operation mode

---

docs/content/docs/getting_started/concepts.adoc
docs/content/docs/operations/cryptographic_material.adoc

docs: configuration for TLS trust stores & update of the pipeline description

---

docs/themes/mytheme/static/js/doc-version-select.js

docs: sort displayed semantic versions with recent displayed first

---

docs/config.yaml
docs/content/_index.adoc
docs/content/docs/guides/nginx.adoc
docs/content/docs/guides/traefik.adoc
docs/content/docs/operations/install.adoc
docs/themes/mytheme/layouts/partials/footer.html

docs: footer updated to have working links

---

.github/workflows/ci.yaml

ci: Dev version of documentation is not deployed anymore if there are no changes to it

---

docs/themes/mytheme/layouts/partials/sidebar/docs-menu.html

docs: Sidebar menu updated to expand only the section to which the currently shown page belongs

---

docs/themes/mytheme/assets/sass/variables.scss
docs/themes/mytheme/layouts/docs/list.html
docs/themes/mytheme/layouts/docs/single.html
docs/themes/mytheme/layouts/partials/last-updated-info.html

docs: Documentation template updated to include the date, when a page has been updated

---

docs/content/docs/configuration/observability/logging.adoc
internal/handler/decision/module.go
internal/handler/management/module.go
internal/handler/prometheus/module.go
internal/handler/proxy/module.go
internal/keystore/module.go
internal/logging/configuration.go
internal/pipeline/authenticators/jwt_authenticator.go
internal/pipeline/authorizers/remote_authorizer.go
internal/pipeline/endpoint/endpoint.go
internal/pipeline/handler_prototype_repository.go
internal/pipeline/hydrators/generic_hydrator.go
internal/rules/composite_error_handler.go
internal/rules/provider/filesystem/file_system.go
internal/rules/repository.go
internal/rules/rule_factory.go
internal/signer/jwt_signer.go
internal/tracing/module.go

feat: Made all log statements adhering to GELF format

---

docs/content/docs/guides/opa.adoc

docs: Integration guide with Open Policy Agent

---

DockerHub-README.md
docs/content/docs/getting_started/proxy_quickstart.adoc

relates to the renaming of the file system provider

docs: renamings forgotten to be done before the release

---

docker/Dockerfile

fix: User for the heimdall process within the container fixed

---

.github/workflows/security.yaml
README.md
go.sum

ci: Made use of CodeQL

---

charts/heimdall/Chart.yaml

relates to #422 and #420 (which closed the first one)
Minor Helm Chart version increased

chore: Helm Chart version increased

---

docs/content/docs/getting_started/decision_service_quickstart.adoc
docs/content/docs/getting_started/proxy_service_quickstart.adoc
docs/content/docs/guides/envoy.adoc
docs/content/docs/guides/nginx.adoc
docs/content/docs/guides/traefik.adoc
examples/README.md
examples/docker-compose/quickstarts/README.md
examples/docker-compose/quickstarts/docker-compose-envoy.yaml
examples/docker-compose/quickstarts/docker-compose-proxy.yaml
examples/docker-compose/quickstarts/docker-compose-traefik.yaml
examples/docker-compose/quickstarts/docker-compose.yaml
examples/docker-compose/quickstarts/envoy-config.yaml
examples/docker-compose/quickstarts/heimdall-config.yaml
examples/docker-compose/quickstarts/upstream-rules.yaml
examples/kind/README.md
examples/kind/kind.yaml
examples/kubernetes/quickstarts/README.md
examples/kubernetes/quickstarts/app.yaml
examples/kubernetes/quickstarts/heimdall.yaml
examples/kubernetes/quickstarts/kustomization.yaml
examples/kubernetes/quickstarts/rules.yaml

closes #407 
closes #408
This PR adds fully working examples for quickstarts and guides described in the documentation. These can also be used to verify the Helm Chart is working (even if not a demo set is done - see #422)

docs: Example setups for docker-compose and kubernetes

---

README.md

Does not relate to any issue
Adds a badge about the released Helm Chart to the README.md file

chore: Helm chart version badge added

---

examples/kubernetes/quickstarts/README.md

none
This PR updates the Kubernetes quick start readme: some of the documented cmd commands were not complete. So, would not lead to the expected result.

chore: commands in k8s quickstart readme updated

---

docs/content/docs/configuration/reference/types.adoc
internal/rules/mechanisms/errorhandlers/matcher/header_matcher.go
internal/rules/mechanisms/errorhandlers/matcher/header_matcher_test.go

closes #473
Fixes the referenced bug

fix: Header value matching using wildcards fixed

---

internal/module.go

None
Just adds a log line on start with the version information before everything else is logged. Only available with "info" log level and below.

feat: Logging of version information on start

---

internal/rules/mechanisms/authenticators/anonymous_authenticator.go
internal/rules/mechanisms/authenticators/basic_auth_authenticator.go
internal/rules/mechanisms/authenticators/generic_authenticator.go
internal/rules/mechanisms/authenticators/jwt_authenticator.go
internal/rules/mechanisms/authenticators/noop_authenticator.go
internal/rules/mechanisms/authenticators/noop_authenticator_test.go
internal/rules/mechanisms/authenticators/oauth2_introspection_authenticator.go
internal/rules/mechanisms/authenticators/unauthorized_authenticator.go
internal/rules/mechanisms/authorizers/allow_authorizer.go
internal/rules/mechanisms/authorizers/cel_authorizer.go
internal/rules/mechanisms/authorizers/deny_authorizer.go
internal/rules/mechanisms/authorizers/remote_authorizer.go
internal/rules/mechanisms/contextualizers/generic_contextualizer.go
internal/rules/mechanisms/errorhandlers/default_error_handler.go
internal/rules/mechanisms/errorhandlers/redirect_error_handler.go
internal/rules/mechanisms/errorhandlers/www_authenticate_error_handler.go
internal/rules/mechanisms/unifiers/cookie_unifier.go
internal/rules/mechanisms/unifiers/header_unifier.go
internal/rules/mechanisms/unifiers/jwt_unifier.go
internal/rules/mechanisms/unifiers/noop_unifier.go

This enables better log analysis and understanding what is going on

refactor: ID logging on mechanism execution

---

examples/docker-compose/quickstarts/upstream-rules.yaml

... to reflect the new structure introduced in 0.7.0-alpha

chore: rule definition in quickstarts updated 

---

internal/rules/repository_impl.go
internal/rules/repository_impl_test.go
internal/rules/rule/factory.go
internal/rules/rule/mocks/factory.go
internal/rules/rule_factory_impl.go

fixes #698 
Fixes the referenced issue.
See https://stackoverflow.com/questions/13476349/check-for-nil-and-nil-interface-in-go and https://groups.google.com/g/golang-nuts/c/wnH302gBa4I?pli=1 for more background

fix: fixes panic on request handling if no rules are available

---

Justfile

As the Dockerfile requires BuildKit-specific variables to be set, it cannot be built with the regular `docker build`, unless the `buildkit` feature is enabled in the docker daemon config. As this is not the default however, explicitly calling `docker buildx build` makes the Justfile work on more devices.

ci: Use docker buildx in Justfile

---

internal/rules/rule_impl.go

closes #718
See PR description

fix: Query parameters are now ignored while matching the request url

---

charts/heimdall/Chart.yaml

... for the upcoming bugfix release

chore: helm chart version updated

---

charts/heimdall/Chart.yaml
charts/heimdall/templates/heimdall/serviceaccount.yaml

This PR has the Helm chart include the chart's fullname in generated RBAC resources to allow for multiple Heimdall installations in a cluster without them overwriting each other.

fix: Include fullname in Helm RBAC resource names

---

internal/rules/provider/cloudblob/provider_test.go
internal/rules/provider/httpendpoint/provider_test.go
internal/rules/provider/kubernetes/provider.go
internal/rules/rule_factory_impl.go

closes https://github.com/dadrus/heimdall/issues/736
This PR fixes the issue mentioned above by moving the filtering logic into the creation, update and deletion functions.
It does make the code less DRY, but I've never written Go before so I'm unsure how to solve this more cleanly.
It furthermore also solves an issue where rewrites have to have all fields set, which is incorrect behavior.
It also contains fixes to make the DNS resolution tests pass more reliably
fix: Fix authClassName filtering
fix: Make DNS resolution tests pass more reliably
fix: Allow rewrites with only a subset of fields set

fix: Working `authClassName` filter if multiple heimdall deployments are present in a cluster

---

charts/heimdall/Chart.yaml
go.sum
internal/rules/provider/kubernetes/provider.go
internal/rules/provider/kubernetes/provider_test.go
internal/rules/rule_factory_impl_test.go

new tests, some code clean up and chart version increase

chore: bugfix release preparation

---

docs/content/docs/configuration/rules/configuration.adoc
docs/content/docs/configuration/rules/default.adoc
internal/rules/rule_factory_impl.go
internal/rules/rule_factory_impl_test.go
internal/x/slicex/filter.go
internal/x/slicex/map.go

closes #773
Implements the feature as described in #773 (see examples there or the updated documentation for how to use)

feat: HTTP method expansion with placeholder key words

---

.github/workflows/ci.yaml

closes #789
With this update the release notes as well as the change log will have a `Documentation` section listing the updates tagged with `docs`.

ci: Release please configured to add a documentation section to release notes

---

.github/workflows/ci.yaml
.goreleaser.yaml

ci: Release binaries job migrated to goreleaser

---

.github/workflows/ci.yaml

chore: Made checking out repository the first step in all jobs

---

charts/heimdall/templates/heimdall/deployment.yaml

closes #826 
Fixes the referenced issue

fix: Quoting configured env vars in helm chart

---

docs/content/docs/guides/contour.adoc

closes #787
New guide explaining integration with [Contour](https://projectcontour.io/)

docs: New integration guide for Contour ingress controller

---

.goreleaser.yaml
docs/content/docs/operations/install.adoc
docs/content/docs/operations/security.adoc

This PR is related to the #808, #810, #867 and #868 PRs.
This PR extends the security related documentation parts by describing how to verify the released binaries and container images, as well on how to get the SBOM and also verify it.

docs: New sections describing signature verification of released archives, container images and the SBOM.

---

internal/rules/mechanisms/authenticators/anonymous_authenticator.go
internal/rules/mechanisms/authenticators/basic_auth_authenticator.go
internal/rules/mechanisms/authenticators/config_decoder.go
internal/rules/mechanisms/authenticators/generic_authenticator.go
internal/rules/mechanisms/authenticators/jwt_authenticator.go
internal/rules/mechanisms/authenticators/oauth2_introspection_authenticator.go
internal/rules/mechanisms/authorizers/cel_authorizer.go
internal/rules/mechanisms/authorizers/config_decoder.go
internal/rules/mechanisms/authorizers/remote_authorizer.go
internal/rules/mechanisms/contextualizers/config_decoder.go
internal/rules/mechanisms/contextualizers/generic_contextualizer.go
internal/rules/mechanisms/errorhandlers/config_decoder.go
internal/rules/mechanisms/errorhandlers/redirect_error_handler.go
internal/rules/mechanisms/errorhandlers/www_authenticate_error_handler.go
internal/rules/mechanisms/finalizers/config_decoder.go
internal/rules/mechanisms/finalizers/cookie_finalizer.go
internal/rules/mechanisms/finalizers/header_finalizer.go
internal/rules/mechanisms/finalizers/jwt_finalizer.go
internal/rules/mechanisms/finalizers/oauth2_client_credentials_finalizer.go
internal/rules/mechanisms/finalizers/oauth2_client_credentials_finalizer_test.go

none
Just some code clean up and simplifications

refactor: Config decoding and validation unified

---

internal/rules/endpoint/authstrategy/api_key.go
internal/rules/endpoint/authstrategy/api_key_test.go
internal/rules/endpoint/authstrategy/basic_auth.go
internal/rules/endpoint/authstrategy/basic_auth_test.go
internal/rules/endpoint/authstrategy/client_credentials.go
internal/rules/endpoint/authstrategy/client_credentials_test.go
internal/rules/endpoint/authstrategy/mapstructure_decoder.go
internal/rules/endpoint/authstrategy/mapstructure_decoder_test.go

refactor: Files and types implementing endpoint auth strategies renamed

---

charts/heimdall/crds/ruleset.yaml

closes #992 
CRD updated to contain proper/better constraints

fix: Making use of better constraints in the definition of the RuleSet CRD to not exceed the k8s rule cost budget

---

docs/content/docs/getting_started/proxy_service_quickstart.adoc

docs: proxy quickstart

---

docs/content/docs/configuration/reference/reference.adoc
example_config.yaml
internal/config/test_data/test_config.yaml
schema/config.schema.json

This PR updates #1043 and adds forgotten json schema update after the last refactorings done in that PR.

chore: OAuth2/OIDC metadata endpoint config fixed (forgotten schema update and tests implemented)

---

.github/workflows/ci.yaml
.github/workflows/security.yaml
docker/Dockerfile
docker/debug.Dockerfile
go.mod

replaces #1173 as this PR covers more affected places

deps: update golang to 1.22.0

---

.github/workflows/ci.yaml
.golangci.yaml

closes #1192 
This PR introduces the use of [Reviewdog](https://github.com/reviewdog/reviewdog) for results from golangci-lint and hadolint.

ci: Using Reviewdog for code and Dockerfile linting

---

docs/themes/mytheme/assets/sass/styles.scss
docs/themes/mytheme/layouts/docs/list.html
docs/themes/mytheme/layouts/docs/single.html
docs/themes/mytheme/layouts/partials/header.html
docs/themes/mytheme/layouts/partials/sidebar/docs-menu.html

This PR concerns the documentation structure and layout. 
feat: optimizes the menu by rearranging the search component and by making the mobile view clearer
fix: side navbar problems with long listings, missing headlines in mobile side navbar, missing "on this page" button with medium viewports, jumps to wrong height of anchors

chore: fix search and mobile menu

---

docs/themes/mytheme/assets/sass/styles.scss
docs/themes/mytheme/layouts/docs/single.html

Little Bugfixes
fix: height alignment menus on the left and an the right
fix: whitespace when "on this page" is expanded on medium sized screens

chore: Align menus and fix whitespace problem

---

docs/content/docs/getting_started/discover_heimdall.adoc
docs/themes/mytheme/assets/sass/styles.scss
docs/themes/mytheme/layouts/partials/header.html
docs/themes/mytheme/layouts/partials/sidebar/docs-menu.html

Shows the search more prominent in a modal. Buttons are shown in docs menu (sidebar) for larger screens and in the header for smaller screens. 
fix: remove doc menu and search button from landing page
fix: adapt search suggestion view container size according to content size
fix: typo in docs

chore: Search Layout

---

docs/themes/mytheme/assets/js/doc-version-select.js

... to fix white links on white background

chore: Made version selection dropdown menu black

---

go.mod
go.sum

* deps: update module github.com/redis/rueidis/rueidisotel to v1.0.32
* deps: update module github.com/redis/rueidis to v1.0.32
* deps: update golang.org/x/exp digest to c7f7c64
* deps: update google.golang.org/genproto/googleapis/rpc digest to 6e1732d

chore: Some dependencies updated

---

docs/content/guides/proxies/traefik.adoc

closes #1079
What the title sais

docs: Traefik integration guide updated to cover global configuration in addition to the route based one

---

docs/content/guides/authz/openfga.adoc

closes #725 
closes #22
New guide addressing integration with any ReBAC system using OpenFGA as an example.

docs: Integration guide for OpenFGA

---

.github/workflows/ci.yaml
renovate.json

closes #1189
Prepares everything to have a better release cadence

ci: Update to renovate and release related CI settings for better release cadence

---

ADOPTERS.md

Added Éphémère Creative as an adopter.

docs: Added Éphémère Creative as an adopter

---

internal/keystore/key_store.go
internal/keystore/key_store_test.go

closes #1562
Fixes the referenced issue

fix: Trailing useless bytes ignored while parsing PEM content

---

internal/rules/mechanisms/finalizers/jwt_signer.go
internal/rules/mechanisms/finalizers/jwt_signer_test.go

closes #1899
CA-issued certificates can now be used in jwt finalizer without the need to add any certificates to heimdall's trust store.

fix: Certificate validation error in JWT finalizer for CA-issued certificates resolved

---

docs/openapi/specification.yaml
examples/kubernetes/quickstarts/heimdall/helm-values.yaml

chore: Forgotten changes related to to the config settings PR

---

docker/Dockerfile

... the used features are already part of the mainstream functionality for longer time

chore: Experimental frontend config removed

---

charts/heimdall/templates/deployment.yaml
charts/heimdall/tests/deployment_test.yaml

closes #2175 
This PR extends the fix done in #1972, adds tests and makes it available for the upcoming patch release

fix: HTTPS scheme configured for the probes if the management service is configured with TLS

---

docs/content/docs/mechanisms/finalizers.adoc
internal/rules/mechanisms/finalizers/jwt_finalizer.go
internal/rules/mechanisms/finalizers/jwt_finalizer_test.go

closes #2137
This PR implements the idea described in the referenced FR.

feat: `jwt` finalizer extended to support templating via `values` property

---

.github/pull-request-template.md

Links to Code of Conduct, Contributing Guidelines and Security Policy were wrong in the Pull Request template.
I updated these to point to the right place.

chore: update pull request template links

---

docs/content/docs/mechanisms/error_handlers.adoc

Update the error handler documentation that previously mentioned http code were not validated, as they are now.
See schema at https://github.com/dadrus/heimdall/blob/main/schema%2Fconfig.schema.json#L1914

chore: Warning related to redirect error handler code usage removed

---

cmd/validate/test_data/config.yaml
schema/config.schema.json

While golang code and documentation references `www_authenticate`, the schema was limiting input to `www-autenticate`. This change synchronizes references so the error handler mode can be used.

fix: www_authenticate error handler schema typo

---

internal/handler/decision/request_context.go
internal/handler/decision/request_context_test.go
internal/handler/envoyextauth/grpcv3/request_context_test.go
internal/handler/proxy/request_context.go
internal/handler/proxy/request_context_test.go

closes #2237
This PR fixes the referenced bug

fix: Multiple header with same name but different values

---

docker/docs.Dockerfile

The `just docs` rule fails with
```
2.456 ERROR: unable to select packages:
2.461   hugo-0.144.0-r0:
2.462     breaks: world[hugo=0.143.0-r0]
```
Bump hugo to [0.144.0](https://github.com/gohugoio/hugo/releases/tag/v0.144.0)-r0.

chore: update hugo package to 0.144.0-r0

---

README.md
docs/content/docs/getting_started/discover_heimdall.adoc
docs/content/guides/authn/oidc_first_party_auth.adoc

Some improvement to the clarify of the docs and rephrasing of sentences.
- ~I have referenced an issue describing the bug/feature request.~
- ~I have added tests that prove the correctness of my implementation.~

docs: improve clarity and some rephrasing

---

README.md

This PR will be merged following the upcoming 0.16.0 release.

chore: SLSA L3 badge added

---

internal/logging/log_factory.go

Minor fix: fall back on "unknown" if `os.Hostname()` failed - not if it succeeded.

fix: Include hostname in log output

---

docs/content/docs/mechanisms/evaluation_objects.adoc

closes #2513
This PR updates the documentation to document the available `networks` CEL extension.

fix(docs): networks CEL extension documented

---

internal/rules/provider/kubernetes/provider.go
internal/rules/provider/kubernetes/provider_test.go
internal/x/testsupport/mock/argument_captor.go

closes #2516
Solves the referenced issue

fix: RuleSet resource status shows correct activeIn values

---

internal/x/radixtree/tree.go
internal/x/radixtree/tree_test.go

fixes #2585
This PR fixes the referenced issue

fix: Correct evaluation of named path params in routes with trailing free wildcard

---

charts/heimdall/crds/ruleset.yaml

fixes #2668
This PR extends the CRD as suggested in the referenced bug report.

fix: CRD updated to include wildcard host expression type
