dadrus/heimdall

.github/semantic.yml, internal/pipeline/authenticators/basic_auth_authenticator.go, internal/pipeline/authenticators/basic_auth_authenticator_test.go, internal/rules/composite_subject_creator.go, internal/rules/composite_subject_creator_test.go
=> fix: authenticator fallback happens now only if the authentication data expected by a failed authenticator is not present.

docs/content/docs/configuration/pipeline/authenticators.md, docs/content/docs/configuration/pipeline/configuration_types.md, docs/content/docs/configuration/pipeline/error_handlers.md, internal/pipeline/errorhandlers/matcher/mapstructure_decoder.go, internal/pipeline/errorhandlers/matcher/mapstructure_decoder_test.go, internal/pipeline/errorhandlers/redirect_error_handler_test.go, internal/pipeline/errorhandlers/www_authenticate_error_handler_test.go, schema/config.schema.json, test_config.yaml
This is a breaking change
closes #52 
closes #53
=> refactor: error types used in error handler error conditions renamed to enhance comprehensibility

internal/fiber/middleware/tracing/options.go, internal/fiber/middleware/tracing/options_test.go, internal/fiber/middleware/tracing/tracer_test.go, internal/handler/decision/handler.go, internal/handler/decision/handler_test.go, internal/handler/decision/module.go, internal/handler/health/handler.go, internal/handler/proxy/module.go
closes #2 
Actually, it doesn't make sense (at least for now) to have separate readyness and lifeness endpoints, as there are no databases and also no conditions, on which heimdall could not be used. For that reason, a simple health endpoint, available under `/.well-known/health` has been implemented.
=> feat: Health endpoint

docs/content/docs/configuration/services/decision_api.adoc, docs/content/docs/guides/traefik.adoc, internal/handler/decision/handler_test.go, internal/handler/decision/module.go
closes #95 
This is already the default behavior for the proxy mode. With this PR it is also true for the decision operation mode
=> feat!: Usage of `trusted_proxies` is mandatory for Decision API to accept `X-Forwarded-*` headers

DockerHub-README.md, docs/content/docs/api/_index.adoc, docs/content/docs/configuration/services/decision_api.adoc, docs/content/docs/getting_started/concepts.adoc, docs/content/docs/getting_started/decision_api_quickstart.adoc, docs/content/docs/guides/traefik.adoc, internal/handler/decision/handler.go, internal/handler/decision/handler_test.go
=> feat!: Make decision endpoint being available directly on the root (`/`) path of the decision service

docs/content/docs/configuration/pipeline/configuration_types.adoc, internal/pipeline/authenticators/extractors/body_parameter_extract_strategy.go, internal/pipeline/authenticators/extractors/body_parameter_extract_strategy_test.go, internal/pipeline/authenticators/extractors/mapstructure_decoder.go, internal/pipeline/authenticators/extractors/mapstructure_decoder_test.go, internal/pipeline/authenticators/jwt_authenticator.go, internal/pipeline/authenticators/jwt_authenticator_test.go, internal/pipeline/authenticators/oauth2_introspection_authenticator.go, internal/pipeline/authenticators/oauth2_introspection_authenticator_test.go, internal/pipeline/contenttype/decoder.go, internal/pipeline/contenttype/json_decoder.go, internal/pipeline/contenttype/www_form_urlencoded_decoder.go
=> feat: Retrieval of an access token from the request body

internal/pipeline/authenticators/extractors/header_value_extract_strategy.go, internal/pipeline/authenticators/extractors/header_value_extract_strategy_test.go
=> fix: Bearer token based authenticators do not feel responsible for the request anymore if no "Bearer" scheme is present in the "Authorization" header.

docs/content/docs/configuration/pipeline/authenticators.adoc, docs/content/docs/configuration/pipeline/configuration_types.adoc, docs/content/docs/configuration/reference/configuration.adoc, internal/config/test_data/test_config.yaml, internal/pipeline/authenticators/basic_auth_authenticator.go, internal/pipeline/authenticators/basic_auth_authenticator_test.go, internal/pipeline/authenticators/extractors/composite_extract_strategy_test.go, internal/pipeline/authenticators/extractors/header_value_extract_strategy.go, internal/pipeline/authenticators/extractors/header_value_extract_strategy_test.go, internal/pipeline/authenticators/extractors/mapstructure_decoder.go, internal/pipeline/authenticators/extractors/mapstructure_decoder_test.go, internal/pipeline/authenticators/jwt_authenticator.go, internal/pipeline/authenticators/jwt_authenticator_test.go, internal/pipeline/authenticators/oauth2_introspection_authenticator.go, internal/pipeline/authenticators/oauth2_introspection_authenticator_test.go, schema/config.schema.json, test_config.yaml
=> refactor!: `strip_prefix` in header authentication data strategy renamed to `schema` to reflect the actual mening and behavior

internal/fiber/middleware/accesslog/accesslog_handler.go
=> fix: accesslog handler does not contain information about authenticated subject if present on errors

docs/content/docs/configuration/pipeline/configuration_types.adoc
=> docs: caution to the description of endpoint configuration added related to the headers, which can be configured

docs/redirect/index.html, docs/themes/mytheme/layouts/partials/header.html, docs/themes/mytheme/static/js/doc-version-select.js
closes #177 
If the required path does not exist in the linked version, a redirect to the main page of the latest released version happens.
=> docs: retain page path while switching between documentation versions

docs/content/docs/configuration/pipeline/authenticators.adoc, docs/content/docs/configuration/pipeline/configuration_types.adoc, docs/content/docs/configuration/reference/configuration.adoc, internal/config/test_data/test_config.yaml, internal/pipeline/authenticators/oauth2_introspection_authenticator.go, internal/pipeline/authenticators/oauth2_introspection_authenticator_test.go, schema/config.schema.json
=> feat: `oauth2_authenticator` updated to optionally support token source selection, like specific header, schema, etc

docs/content/docs/configuration/pipeline/authenticators.adoc, docs/content/docs/configuration/pipeline/configuration_types.adoc, docs/content/docs/configuration/reference/configuration.adoc, internal/config/test_data/test_config.yaml, internal/pipeline/authenticators/generic_authenticator.go, internal/pipeline/authenticators/generic_authenticator_test.go, internal/pipeline/authenticators/jwt_authenticator.go, internal/pipeline/authenticators/jwt_authenticator_test.go, internal/pipeline/authenticators/oauth2_introspection_authenticator.go, internal/pipeline/authenticators/oauth2_introspection_authenticator_test.go, internal/pipeline/authenticators/subject_info.go, internal/pipeline/authenticators/subject_info_test.go, schema/config.schema.json, test_config.yaml
Affected authenticators are `generic`, `oauth2` and `jwt` authenticator.
Renamed and refactored property is `session` which had the following structure:
```yaml
session:
subject_id_from: <some template>
subject_attributes_from: <some template>
```
This PR changes it to
```yaml
subject:
id: <some template>
attributes: <some template>
```
=> refactor!: `session` property used by some authenticators renamed (incl. its properties) to `subject` to better reflect its meaning

internal/keystore/module.go, internal/keystore/module_test.go
=> refactor!: ECDSA P-384 key is generated instead of RSA-2048 for JWT signing purposes on startup if no key store has been configured

docs/content/docs/operations/observability.adoc, internal/fiber/middleware/accesslog/accesslog_handler.go, internal/fiber/middleware/accesslog/accesslog_handler_test.go, internal/fiber/middleware/logger/logger.go, internal/fiber/middleware/logger/logger_handler.go, internal/fiber/middleware/logger/logger_handler_test.go, internal/handler/decision/module.go, internal/handler/management/module.go, internal/handler/proxy/module.go, internal/testsupport/testing_log.go, internal/tracing/module_test.go, internal/x/opentelemetry/tracecontext/tracecontext.go
closes #142 
This PR adds `_trace_id`, `_span_id` and `_parent_id` (parent span id) to any emitted log event if tracing is enabled.
=> feat: Support for log, trace and request correlation

docs/content/docs/configuration/pipeline/overview.adoc
closes #295 
The functionality suggested in #295 was already in place. Only the corresponding documentation was missing.
=> docs: Description for RequestURL, available as part of the request context to the pipeline handlers, adjusted.

docs/content/docs/configuration/pipeline/authorizers.adoc, docs/content/docs/guides/opa.adoc
closes #296 
Support for #296 is actually already implemented and can be done using a combination of corresponding authenticators and a `local` authorizer. Latter can then be used to implement the required enforcement. Corresponding example has been added by the PR to the documentation.
=> docs: Documentation for local authorizer updated to include examples with HTTP method based access enforcement

docs/content/docs/configuration/services/configuration_types.adoc, internal/config/configuration.go, internal/config/mapstructure_decoder.go, internal/config/mapstructure_decoder_test.go, internal/config/serve.go, internal/config/serve_test.go, internal/config/test_data/test_config.yaml, internal/handler/decision/module.go, internal/handler/listener/listener.go, internal/handler/listener/listener_test.go, internal/handler/management/module.go, internal/handler/proxy/module.go, internal/testsupport/test_decoder.go, schema/config.schema.json, test_config.yaml
closes #152 
Minimal supported version is TLS 1.2 and only PFS cipher suites can be configured (see below). 
The tls configuration has been extended and looks now as follows:
```.yaml
key: <path to the private key in PEM format>
cert: <path to the PEM file containing the certificate and optionally the intermediate CA certificates>
cipher_suites:
- TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
- ...
min_version: TLS1.2 # or TLS1.3
```
`cipher_suites` can be configured with the following values:
- TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
- TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
- TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
- TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
- TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
- TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
- TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
- …
=> feat: Configuration of minimal TLS version and the required cipher suites

docs/content/docs/configuration/reference/configuration_reference.adoc, docs/content/docs/configuration/reference/configuration_types.adoc, docs/content/docs/configuration/rules/providers.adoc, go.mod, go.sum, internal/config/test_data/test_config.yaml, internal/endpoint/endpoint.go, internal/endpoint/endpoint_test.go, internal/httpcache/round_tripper.go, internal/httpcache/round_tripper_test.go, internal/rules/provider/httpendpoint/provider_test.go, internal/rules/provider/httpendpoint/ruleset_endpoint.go, internal/rules/provider/httpendpoint/ruleset_endpoint_test.go, schema/config.schema.json, test_config.yaml
closes #272 
This PR extends the `endpoint` definition to support a new configuration property: `enable_http_cache` of type `bool`. If set to `true` strict caching according to [RFC 7234](https://www.rfc-editor.org/rfc/rfc7234) will be used. 
For pipeline handlers the value of `enable_http_cache` defaults to `false`. for the httpendpoint provider (to load the rule sets from arbitrary HTTP(s) endpoints) it defaults to `true`.
If the service does not set set any related headers in the response, thus no expiration information is available, heuristic freshness lifetime calculation is not done. Instead such responses are not cached.
=> feat: HTTP caching according to RFC 7234 is supported by pipeline handlers and the httpendpoint provider

.github/workflows/ci.yaml, DockerHub-README.md, README.md, docs/content/docs/configuration/reference/configuration_reference.adoc, docs/content/docs/configuration/reference/configuration_types.adoc, docs/content/docs/configuration/rules/providers.adoc, docs/content/docs/operations/cli.adoc, docs/content/docs/operations/security.adoc, go.sum
addresses:
* typos found in documentation or other things forgotten to write
* readme updates
* flickering tests
* ci job misconfigurations found during the last release
=> chore: Last polishings for the next release

docs/content/docs/configuration/pipeline/authorizers.adoc, docs/content/docs/configuration/reference/configuration_reference.adoc, docs/content/docs/guides/opa.adoc, internal/config/test_data/test_config.yaml, internal/pipeline/authorizers/cel_authorizer.go, internal/pipeline/authorizers/cel_authorizer_test.go, internal/pipeline/authorizers/cellib/library.go, internal/pipeline/authorizers/expression.go, internal/pipeline/authorizers/remote_authorizer.go, internal/pipeline/authorizers/remote_authorizer_test.go, internal/pipeline/subject/subject.go, schema/config.schema.json
addresses #329 
This PR introduces a **breaking change** and changes the way how the `remote` authorizer can handle structured responses from the endpoint (authorization system) it uses. Before this PR, one could optionally use a `script` property to check the response. With this PR this property is replaced by the `expressions` property (still optional), which can have a list of CEL expressions.
The following example shows the changes in detail:
Given an OPA policy available under `https://opa.local/v1/data/share_photos/policy/allow` which results in `{"result": true}` if authorization was successful.
**Old Config**:
```.yaml
id: photos_access
type: remote
config:
endpoint:
url: https://opa.local/v1/data/share_photos/policy/allow
payload: |
{ "input": { "user": {{ quote .Subject.ID }}, …
```
=> refactor!: Remote authorizer uses CEL instead of ECMAScript for response verification purposes

internal/pipeline/errorhandlers/matcher/header_matcher.go, internal/pipeline/errorhandlers/matcher/header_matcher_test.go
=> fix: `request_headers` error condition implementation fixed

docs/content/docs/configuration/reference/types.adoc, docs/content/docs/configuration/rules/pipeline_mechanisms/authenticators.adoc, internal/config/test_data/test_config.yaml, internal/endpoint/mapstructure_decoder.go, internal/endpoint/mapstructure_decoder_test.go, internal/rules/mechanisms/authenticators/config_decoder.go, internal/rules/mechanisms/authorizers/config_decoder.go, internal/rules/mechanisms/contextualizers/config_decoder.go, internal/rules/provider/httpendpoint/config_decoder.go, schema/config.schema.json
This PR closes #273
With this PR an endpoint can not only be configured in a structured way, like
```.yaml
endpoint:
url: http://foo.bar
```
but also like
```.yaml
endpoint: http://foo.bar
```
which will reduce the amount of yaml code, if only the actual URL is required to be configured and the remaining parts of the endpoint configuration can remain mechanism default.
=> feat: Simpler endpoint configuration

docs/content/docs/getting_started/configuration_introduction.adoc, go.mod, go.sum, internal/config/parser/yaml.go, internal/config/parser/yaml_test.go, internal/config/test_data/test_config.yaml
This PR closes #67 
Example configuration which shows the new possibility.
```.yaml
id: hydra_authenticator
type: oauth2_introspection
config:
introspection_endpoint:
url: http://hydra:4445/oauth2/introspect
auth:
type: basic_auth
config:
user: ${INTROSPECT_EP_USER}
password: ${INTROSPECT_EP_PASSWORD}
```
=> feat: Support for environment variables substitution in config file

docs/content/docs/configuration/rules/pipeline_mechanisms/authorizers.adoc, docs/content/docs/configuration/rules/pipeline_mechanisms/contextualizers.adoc, docs/content/docs/configuration/rules/pipeline_mechanisms/overview.adoc, docs/content/docs/configuration/rules/pipeline_mechanisms/unifiers.adoc, internal/rules/mechanisms/authorizers/remote_authorizer_test.go, internal/rules/mechanisms/contextualizers/generic_contextualizer_test.go, internal/rules/mechanisms/template/template.go, internal/rules/mechanisms/template/template_test.go, internal/rules/mechanisms/template/types.go
Before this PR the access to different request properties in a template happened via special purpose methods as shown below:
```.yaml
"request_method": {{ quote .RequestMethod }},
"request_url": {{ quote .RequestURL }},
"client_ips": {{ .RequestClientIPs }}
"x_foo_value": {{ .RequestHeader "X-Foo" | quote }}
"x_cookie": {{ .RequestCookie "x_cookie" | quote }}
```
This PR changes the access to the same information via a `Request` object:
```.yaml
"request_method": {{ quote .Request.Method }},
"request_url": {{ quote .Request.URL }},
"client_ips": {{ .Request.ClientIP }}
"x_foo_value": {{ .Request.Header "X-Foo" | quote }}
"x_cookie": {{ .Request.Cookie "x_cookie" | quote }}
```
This way, both templates, as well as CEL expressions make use of the same underlying data structures.
=> refactor!: Objects and functions available in templates and CEL expressions harmonized

Justfile
Not related to any documented issue
After moving the `Version` type into its own module, the `build` recipe in Justfile has not been updated. That rendered local builds useless regarding the embedded version information - it was just not set until this PR.
=> chore: build recipe in Justfile fixed to reference the proper module for embedding version information

docs/content/docs/configuration/cryptographic_material.adoc, docs/content/docs/configuration/reference/reference.adoc, docs/content/docs/configuration/reference/types.adoc, docs/content/docs/configuration/services/decision.adoc, docs/content/docs/configuration/services/management.adoc, docs/content/docs/configuration/services/proxy.adoc, example_config.yaml, internal/config/key_store.go, internal/config/serve.go, internal/config/signer.go, internal/config/test_data/test_config.yaml, internal/handler/listener/listener.go, internal/handler/listener/listener_test.go, internal/rules/provider/cloudblob/provider_test.go, internal/signer/jwt_signer.go, internal/signer/jwt_signer_test.go, schema/config.schema.json
relates to #274
This PR introduces a dedicated configuration type for Key Stores:
```.yaml
key_store: 
path: /path/to/keystore.pem
password: SomePassword
```
On one hand, that would be required anyway, when #274 will be addressed (in sense of the configuration new `type` property will be introduced). On the other hand, it makes the documentation less repetitive and allows better handling of key stores in code by having same structures for all available key stores, without the need to know, for which purpose it was configured.
However, this PR does also introduce a breaking change. Here an overview, how key stores were configured before this PR, and how they have to be configured after this PR is merged:
Old `tls` configuration:
```.yaml
tls:
key_store: /path/to/keystore.pem
password: …
```
=> refactor!: New type for key store configuration introduced

charts/heimdall/README.adoc, charts/heimdall/templates/demo/configmap.yaml, charts/heimdall/templates/heimdall/deployment.yaml, charts/heimdall/values.yaml
Does not relate to any
This PR enables configuration of arbitrary environment variables for heimdall deployments. E.g. if you can't rely on defaults and have to set OTEL specific variables, you can either create an additional values yaml file like shown below and provide it via the `-f` flag to helm, or just set the required variables via CLI as also shown below.
In addition this PR changes the log format for the demo deployment from text to gelf
**Example 1:** Providing OTEL environment variables via CLI
```.bash
helm install heimdall -n heimdall --create-namespace  \
--set env.OTEL_EXPORTER_OTLP_TRACES_PROTOCOL=grpc  \
--set env.OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://tempo.tempo.svc.cluster.local:4317 \
dadrus/heimdall
```
**Example 2:** Providing OTEL environment variables via …
=> feat: Helm chart supports setting of arbitrary environment variables

.github/workflows/ci.yaml, Justfile, charts/heimdall/templates/NOTES.txt, charts/heimdall/templates/demo/configmap.yaml, charts/heimdall/templates/demo/deployment.yaml, charts/heimdall/templates/demo/ingress.yaml, charts/heimdall/templates/demo/namespace.yaml, charts/heimdall/templates/demo/service.yaml, charts/heimdall/templates/demo/test-rule.yaml, charts/heimdall/templates/heimdall/configmap.yaml, charts/heimdall/values.yaml
None
This PR streamlines the names of properties, which enable or disable something. Here the affected property is `demo.enable`, which has been renamed to `demo.enabled`.
=> refactor!: `demo.enable` in helm chart renamed to `demo.enabled`

.github/workflows/ci.yaml
... otherwise the helm chart is released before the docker images are available on docker hub
=> ci: Made helm chart release job dependent on docker images release job

internal/rules/mechanisms/errorhandlers/matcher/error_condition_matcher_test.go, internal/rules/mechanisms/errorhandlers/matcher/header_matcher.go, internal/rules/mechanisms/errorhandlers/matcher/header_matcher_test.go
closes #472
Closes a bug related to header matching during error handler execution
=> fix: Header matching case-sensitivity fixed

docs/content/docs/configuration/reference/reference.adoc, docs/content/docs/configuration/services/decision.adoc, internal/config/test_data/test_config.yaml, internal/handler/decision/app.go, schema/config.schema.json
None
CORS just doesn't make any sense for APIs used by backend services only. And the API exposed by the decision service falls exactly into this category.
=> refactor!: CORS support for decision service removed

cmd/validate.go, cmd/validate/config_test.go, cmd/validate/ruleset.go, cmd/validate/ruleset_test.go, cmd/validate/test_data/config.yaml, cmd/validate/test_data/ruleset.yaml, internal/config/configuration.go, internal/config/configuration_test.go, internal/config/default_configuration.go
closes #7 
This PR implements a command to validate rule sets as it already possible to validate configuration.
Example:
```
heimdall validate rules -c <path to config yaml> <path to rules file>
```
unlike config validation, which just performs schema validation, rules validation loads the configuration and instantiates rules, respectively the corresponding objects, exactly as heimdall would do this when started.
=> feat: Command for validation of rules

cmd/health.go, internal/config/parser/env.go, internal/config/parser/yaml.go, internal/config/validator.go, internal/endpoint/api_key_strategy.go, internal/endpoint/basic_auth_strategy.go, internal/endpoint/client_credentials_strategy.go, internal/endpoint/endpoint.go, internal/fasthttp/opentelemetry/client.go, internal/fiber/middleware/accesslog/accesslog_handler.go, internal/fiber/middleware/proxyheader/proxy_header.go, internal/fiber/middleware/xfmphu/request_url.go, internal/handler/envoyextauth/grpcv3/middleware/errorhandler/error_response.go, internal/httpcache/round_tripper.go, internal/keystore/key_store.go, internal/rules/config/matcher.go, internal/rules/mechanisms/authenticators/basic_auth_authenticator.go, internal/rules/mechanisms/authenticators/generic_authenticator.go, internal/rules/mechanisms/authenticators/jwt_authenticator.go, internal/rules/mechanisms/authenticators/oauth2_introspection_authenticator.go, internal/rules/mechanisms/authorizers/remote_authorizer.go, internal/rules/mechanisms/contenttype/www_form_urlencoded_decoder.go, internal/rules/mechanisms/contextualizers/generic_contextualizer.go, internal/rules/mechanisms/oauth2/numeric_date.go, internal/rules/mechanisms/template/template.go, internal/rules/mechanisms/unifiers/jwt_unifier.go, internal/signer/jwt_signer.go, internal/x/stringx/stringx.go
uses the new Go 1.20 unsafe functionality
=> perf: converting byte slice to a string and vice versa without memory allocation

docs/content/docs/configuration/reference/reference.adoc, docs/content/docs/configuration/rules/pipeline_mechanisms/unifiers.adoc, internal/config/test_data/test_config.yaml, internal/rules/mechanisms/unifiers/jwt_unifier.go, internal/rules/mechanisms/unifiers/jwt_unifier_test.go, schema/config.schema.json
closes #663 
Implements the idea described in #663.
=> feat: `jwt` unifier supports definition of a custom header and scheme

go.sum, internal/x/pkix/validate_certificate.go
closes #670 
This fix updates the certificate validation implementation to not create a new cert pool if there are no root certificates configured. That way the system trust store will be used in such cases. Without that fix, the system trust store will never be used, leading to the issue described in #670
=> fix: Proper usage of system trust store for certificate validation purposes

internal/fiber/middleware/xfmphu/handler_test.go, internal/fiber/middleware/xfmphu/request_url.go
=> fix: Leading slash is not added to the URL path anymore during URL path extraction

docs/content/docs/configuration/reference/reference.adoc, docs/content/docs/configuration/reference/types.adoc, docs/content/docs/configuration/services/decision.adoc, docs/content/docs/configuration/services/management.adoc, docs/content/docs/configuration/services/proxy.adoc, go.mod, go.sum, internal/config/configuration.go, internal/config/default_configuration.go, internal/config/mapstructure_decoder.go, internal/config/mapstructure_decoder_test.go, internal/config/parser/merge.go, internal/config/serve.go, internal/config/test_data/test_config.yaml, internal/handler/decision/app.go, internal/handler/envoyextauth/grpcv3/service.go, internal/handler/management/app.go, internal/handler/proxy/app.go, schema/config.schema.json
closes #704
Introduces a new property to define the read and write buffer sizes for the incoming request and the outgoing responses. The following property is supported for all services exposed by heimdall, so the decision, the proxy and the management service:
```yaml
buffer_limit:
read: 1MB
write: 10KB
```
=> feat: Configuration for read and write buffer sizes

internal/cache/memory/cache.go, internal/cache/memory/cache_test.go
See discussion in discord: https://discord.com/channels/1100447190796742698/1100447191358787646/1121328565879836732
The library used by heimdall extends the ttl of cached object if not explicitly disabled. That was not done in heimdall leading to extending the ttl of e.g. cached JWTs resulting in expired JWTs being returned to the calling proxy, respectively forwarded to the upstream service.
=> fix: Refresh of cached items disabled to avoid retrieval of stale items

internal/fiber/middleware/xfmphu/request_url.go, internal/handler/proxy/handler_test.go, internal/handler/requestcontext/request_context.go
closes #715 
Fixes the duplicate url encoding
=> fix: URL encoding fixed while forwarding the request to the upstream in proxy mode

internal/rules/repository_impl_test.go, internal/rules/rule_impl.go, internal/rules/rule_impl_test.go
=> fix: Matcher expressions do not have to cope with url encoded path fragments any more if such are present

charts/heimdall/templates/demo/deployment.yaml, charts/heimdall/templates/heimdall/deployment.yaml
closes #701
Adds an annotation as described in https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments
This should automatically ensure a zero-downtime restart of the heimdall pods should the values and by extension the ConfigMap be updated via `helm upgrade`.
=> feat: Support for automatically Helm roll deployments

.github/ISSUE_TEMPLATE/DOCS-ISSUE-REPORT.yaml
closes #682 
New template, which makes it easier to file issues related to documentation.
=> ci: New template to file documentation issues

docs/content/docs/configuration/rules/pipeline_mechanisms/authorizers.adoc, docs/content/docs/configuration/rules/pipeline_mechanisms/contextualizers.adoc, internal/config/test_data/test_config.yaml, internal/rules/mechanisms/authorizers/remote_authorizer.go, internal/rules/mechanisms/authorizers/remote_authorizer_test.go, internal/rules/mechanisms/contextualizers/generic_contextualizer.go, internal/rules/mechanisms/contextualizers/generic_contextualizer_test.go, schema/config.schema.json
closes #686
Makes following possible:
```yaml
- id: openfga
config:
endpoint: # etc.
payload: |
{
"user": "user:{{ .Subject.ID }}",
"relation": {{ quote .Values.relation }},
"resource": {{ quote .Values.resource }}
}
```
and then used in a pipeline like
```yaml
- authorizer: openfga
config:
values:
relation: read
resource: "endpoint:foo"
```
which will result in the following json payload sent to the defined endpoint for the `.Subject.ID` being `1`:
```json
{
"user": "user:1",
"relation": "read",
"resource": "endpoint:foo"
}
```
If the `values` property is defined in the configuration of the particular mechanism, the corresponding entries act as defaults for the rule pipeline making use of that mechanism.
=> feat: Values object can be used in payload of generic contextualizer and remote authorizer

.github/workflows/ci.yaml, DockerHub-README.md
closes #782 
Makes the images built after merges into main available in the container registry. These images are tagged with just the `dev` suffix and with the `dev-<SHA>` suffix, where the SHA is the commit in heimdall main from which it was created.
For example, after a build at commit `730b2206`, an image will be created for `dadrus/heimdall:dev-730b2206fdfc688ca42bcdf0e344d8fa6bfba232` and the image `dadrus/heimdall:dev` will be tagged to it until the next build.
=> ci: CI pipeline updated to publish container images built after merging PRs into main

.github/workflows/ci.yaml
closes #785
Usage of `run: echo "::set-output name={name}::{value}"` replaced with `run: echo "{name}={value}" >> $GITHUB_OUTPUT`
=> ci: Not using deprecated set-output in pipeline jobs anymore

.github/semantic.yml, renovate.json
closes #786 
This PR configures the semantic plugin to allow `deps` as a commit tag and configures renovate to use it for its PRs.
=> ci: Renovate is using `deps` for its PRs to have autorelease create PRs for updates only

.github/workflows/ci.yaml, .goreleaser.yaml
closes #758
This PR updates the CI release pipeline to sign every artifact published in a release using a so called "keyless signing" supported by cosign (See [here](https://docs.sigstore.dev/cosign/signing_with_blobs/#keyless-signing-of-blobs-and-files) for more details).
Verification of the released binaries can happen using [cosign](https://github.com/sigstore/cosign) as follows:
```bash
cosign verify-blob <path to the artifact> \
--certificate <path to the certificate> \
--signature <path to the signature file> \
--certificate-identity=https://github.com/dadrus/heimdall/.github/workflows/ci.yaml@refs/heads/main \
--certificate-oidc-issuer=https://token.actions.githubusercontent.com
```
=> ci: Cosign configured to sign released binaries

.github/workflows/ci.yaml, .goreleaser.yaml
closes #724 
This PR updates the CI release pipeline to sign every published container image using a so called "keyless signing" supported by cosign (See [here](https://docs.sigstore.dev/cosign/signing_with_containers/) for more details).
Verification of the published images can happen using [cosign](https://github.com/sigstore/cosign) as follows:
```bash
cosign verify dadrus/heimdall:<released version> \
--certificate-identity=https://github.com/dadrus/heimdall/.github/workflows/ci.yaml@refs/heads/main \
--certificate-oidc-issuer=https://token.actions.githubusercontent.com
```
=> ci: Cosign configured to sign published images

charts/heimdall/README.adoc, charts/heimdall/templates/heimdall/deployment.yaml, charts/heimdall/values.yaml
closes #822
Implements the option described in the referenced ticket. This allows starting heimdall for integration with envoy v3 ext_auth, when installing via helm chart and enables usage of further flags, which might come in the future.
=> feat: Helm chart enhanced to allow passing optional arguments to heimdall

docs/content/docs/configuration/rules/pipeline_mechanisms/authenticators.adoc, internal/signer/jwt_signer.go, internal/signer/jwt_signer_test.go
Not really, but many complains and people wondering, why it is the case
With that update, you can use self-signed certificates (highly discouraged for production), respectively the corresponding keys to e.g. sign the JWTs issued by heimdall without the need to make the self-signed certificate present in the system-wide trust store.
Before the change introduced with this PR, heimdall would log `x509: certificate signed by unknown authority` and refuse starting.
=> fix: Validation of a self-signed certificate does not require its presence in the system wide trust store any more

.github/workflows/ci.yaml
As the CycloneDX/gh-gomod-generate-sbom, repectively cyclonedx-gomod, which is used to generate the SBOM is compiled using go version < 1.21 and heimdall makes use of the new std lib features, there is a need to have the proper go version  (1.21) installed locally. Otherwise `go list` will fail as some of the used packages are unknown.
=> ci: fix for the SBOM generation

.github/workflows/ci.yaml
v4 is in beta and is not officially available
=> chore: codecov downgraded to v3

docs/content/docs/configuration/reference/reference.adoc, docs/content/docs/configuration/reference/types.adoc, internal/config/test_data/test_config.yaml, internal/rules/endpoint/authstrategy/client_credentials_strategy.go, internal/rules/endpoint/authstrategy/mapstructure_decoder.go, internal/rules/endpoint/authstrategy/mapstructure_decoder_test.go, schema/config.schema.json
none
This PR unifies the names for the OAuth Client Credentials Grant flow implementation used for finalizers and endpoint auth strategy. Latter has been renamed from `client_credentials` to `oauth2_client_credentials` (which is also used for a finalizer).
The following examples highlights the changes
```yaml
endpoint:
url: http://foo.bar
method: GET
headers:
bla: bla
auth:
type: oauth2_client_credentials # was client_credentials before
config:
auth_method: request_body
token_url: http://bar.foo
client_id: foo
client_secret: bar
cache_ttl: 20s
header:
name: X-Foo
scheme: Bar
```
=> refactor!: Endpoint specific `client_credentials` auth strategy renamed to `oauth2_client_credentials`

charts/heimdall/crds/ruleset.yaml
closes #991
Makes usage of HTTP method expansion possible, as this is also the case in regular rulesets
=> fix: HTTP method expansion in k8s RuleSet resources

internal/rules/mechanisms/finalizers/jwt_finalizer.go, internal/rules/mechanisms/finalizers/jwt_finalizer_test.go
... it has been added by accident but never documented. The Request object should also not be used from a JWT finalizer.
=> chore: Access to Request object disabled for the JWT finalizer

.github/workflows/ci.yaml, docs/content/docs/configuration/rules/providers.adoc, docs/content/docs/getting_started/decision_service_quickstart.adoc, docs/content/docs/operations/install.adoc, docs/content/docs/operations/security.adoc
none
This PR updates the CI pipeline to publish the built container images to GHCR in addition to DockerHub.
In addition, this PR publishes the created container signatures and SBOM attestations to separate repositores/packages to avoid scattering of version/tag information in the "main" repository.
=> feat: Container images are published to GHCR in addition to DockerHub

internal/cache/cache.go, internal/cache/memory/cache.go, internal/cache/memory/cache_test.go, internal/cache/mocks/cache.go, internal/cache/noop_cache.go, internal/httpcache/round_tripper.go, internal/rules/endpoint/authstrategy/client_credentials_test.go, internal/rules/mechanisms/authenticators/generic_authenticator.go, internal/rules/mechanisms/authenticators/generic_authenticator_test.go, internal/rules/mechanisms/authenticators/jwt_authenticator.go, internal/rules/mechanisms/authenticators/jwt_authenticator_test.go, internal/rules/mechanisms/authenticators/oauth2_introspection_authenticator.go, internal/rules/mechanisms/authenticators/oauth2_introspection_authenticator_test.go, internal/rules/mechanisms/authorizers/remote_authorizer.go, internal/rules/mechanisms/authorizers/remote_authorizer_test.go, internal/rules/mechanisms/contextualizers/generic_contextualizer.go, internal/rules/mechanisms/contextualizers/generic_contextualizer_test.go, internal/rules/mechanisms/finalizers/jwt_finalizer.go, internal/rules/mechanisms/finalizers/jwt_finalizer_test.go, internal/rules/mechanisms/finalizers/oauth2_client_credentials_finalizer_test.go, internal/rules/oauth2/clientcredentials/clientcredentials.go, internal/rules/oauth2/clientcredentials/clientcredentials_test.go
relates to #999
This PR extends the `Cache` interface as described in the title. That decouples the development of #999 from potential package changes and allows parallel implementation of other cache types.
=> refactor: Cache interface expects a `Context` object as first argument

docs/content/docs/configuration/rules/pipeline_mechanisms/authorizers.adoc, docs/content/docs/configuration/rules/pipeline_mechanisms/contextualizers.adoc, docs/content/docs/configuration/rules/pipeline_mechanisms/overview.adoc, internal/rules/mechanisms/authorizers/remote_authorizer.go, internal/rules/mechanisms/authorizers/remote_authorizer_test.go, internal/rules/mechanisms/contextualizers/generic_contextualizer.go, internal/rules/mechanisms/contextualizers/generic_contextualizer_test.go, internal/rules/mechanisms/values/values.go, internal/rules/mechanisms/values/values_test.go
closes #1039
This PR adds support for `values` templating in `generic` contextualizer and `remote` authorizer to allow functionality requested in #1039. With that in place, the configuration option sketched below is now possible.
In heimdall config file:
```yaml
mechanisms:
authorizers:
- id: openfga_check
type: remote
config:
endpoint:
url: https://openfga.local
payload: |
{
"user": {{ .Subject.ID }},
"relation": {{ .Values.relation | quote }},
"object": {{ .Values.object | quote }}
}
```
In your rule set:
```yaml
rules:
- authorizer: openfga_check
config:
values:
relation: can_delete
object: "{{ index (splitList "/" .Request.URL.Path) 2 }}"
```
=> feat: Templating support in `remote` authorizer and `generic` contextualizer `values` property

charts/heimdall/README.adoc, charts/heimdall/values.yaml
closes #1049
As stated in the title of this PR, it changes the helm chart configuration to pull heimdall images from ghcr.io instead of pulling them from DockerHub.
If pulling the container image is desired to happen from DockerHub, one can set `image.repository` to `dadrus/heimdall`  while using the chart.
=> feat: Helm chart pulls heimdall container image from ghcr.io instead from DockerHub

internal/rules/mechanisms/authenticators/extractors/body_parameter_extract_strategy_test.go, internal/rules/mechanisms/contenttype/decoder.go
closes #1058
Before this PR, the content type decoder expected the `application/x-www-form-urlencoded` MIME type as is while dispatching between different decoder implementations. This fix takes into account that a MIME type can have parameters.
=> fix: MIME type decoder covers optional parameters

docs/content/docs/configuration/rules/pipeline_mechanisms/overview.adoc, internal/handler/requestcontext/request_context.go, internal/handler/requestcontext/request_context_test.go
relates to #889
Before the referenced PR, the call to `Request.Header(name)` returned a string containing all values for all header occurrences in the request with the same name separated by a comma. During the migration from fasthttp to build-in http engine that behavior has been changed to return only the first values of a header, even if the actual header contents were a comma separated list of multiple  values.
This PR recovers this functionality.
=> refactor: Recover retrieval of header values as it was before #889

docs/content/docs/configuration/rules/pipeline_mechanisms/overview.adoc, internal/handler/envoyextauth/grpcv3/request_context.go, internal/handler/envoyextauth/grpcv3/request_context_test.go, internal/handler/requestcontext/request_context.go, internal/heimdall/context.go, internal/rules/cel_execution_condition_test.go, internal/rules/mechanisms/authorizers/cel_authorizer_test.go, internal/rules/mechanisms/cellib/requests_test.go, internal/rules/mechanisms/errorhandlers/matcher/error_condition_matcher.go, internal/rules/mechanisms/errorhandlers/matcher/error_condition_matcher_test.go, internal/rules/mechanisms/template/template_test.go
The type of `Request.ClientIP` property was always an array of strings. Unfortunately, the name `ClientIP` does not reflect this and is misleading. This PR resolves this by renaming this property to `ClientIPAddresses`.
=> refactor!: `Request.ClientIP` renamed to `Request.ClientIPAddresses` to reflect the actual contents

charts/heimdall/crds/ruleset.yaml, docs/content/docs/configuration/rules/configuration.adoc, internal/handler/requestcontext/extract_url.go, internal/handler/requestcontext/extract_url_test.go, internal/rules/config/backend.go, internal/rules/config/decoder.go, internal/rules/config/parser.go, internal/rules/config/parser_test.go, internal/rules/config/rule.go, internal/rules/config/rule_set.go, internal/rules/config/url_rewriter.go, internal/rules/config/url_rewriter_test.go, internal/rules/rule_factory_impl.go, internal/rules/rule_factory_impl_test.go, internal/rules/rule_impl.go, internal/rules/rule_impl_test.go
closes #1070
This PR implements an explicit opt-in for url-encoded slashes in URL paths, used while matching a request in all operation modes, as well as when forwarding the request to the upstream service in proxy mode.
The new rule-level configuration property is named `allow_encoded_slashes` and can be set to the following values:
* `off` - Reject requests containing encoded slashes. Means, if the request URL contains an url-encoded slash (`%2F`), the rule will not match it. This is also the default setting, if the property is not configured explicitly.
* `on` - Accept requests using encoded slashes, decoding them and making it transparent for the rules and the upstream url. That is, the `%2F` becomes a `/` and will be treated as such in all places.
* `no_decode` - Accept requests …
=> feat: Opt-In for url-encoded slashes in URL paths

internal/rules/mechanisms/authenticators/jwt_authenticator.go, internal/rules/mechanisms/authenticators/jwt_authenticator_test.go, internal/rules/oauth2/clientcredentials/clientcredentials.go, internal/rules/oauth2/clientcredentials/clientcredentials_test.go
Not documented. Encountered during the review of #1043 
In many places, heimdall implements useful defaults. Among other things, these are HTTP headers. On of such defaults is the `Accept` header, which has unfortunately been set as `Accept-Type`, which just does not exist. In principle, there should not be any issues because of this, as many implementations are just ignoring such headers, especially in m2m contexts.
=> fix: Accept header usage

charts/heimdall/README.adoc, charts/heimdall/templates/heimdall/deployment.yaml, charts/heimdall/values.yaml
No related issue, discussed in discord (https://discord.com/channels/1100447190796742698/1192143563039973529/1192143563039973529).
Adds the possibility to reference other secrets and configmaps in the heimdall config, in order to consume values from other deployed softwares.
=> feat: Helm chart supports setting environment variables by referencing either a ConfigMap or a Secret via `envFrom`

go.sum
=> chore: Prune old dependencies

docs/config.yaml
n/a
This PR solves problems running asciidoctor through newer versions starting with version 0.91 of hugo as described in https://stackoverflow.com/a/71734790
=> chore: Add security-config for hugo, so that gems of asciidoctor can be loaded in newer hugo-versions

docs/content/docs/configuration/types.adoc, internal/rules/mechanisms/authenticators/jwt_authenticator_test.go, internal/rules/mechanisms/authenticators/oauth2_introspection_authenticator_test.go, internal/rules/mechanisms/oauth2/claims_test.go, internal/rules/mechanisms/oauth2/expectations.go, internal/rules/mechanisms/oauth2/expectations_test.go, internal/x/slicex/intersection.go
closes #1234
Fixes the assertion of the `aud` claim in JWTs and OAuth2 introspection endpoint responses. It adheres now to the definition in [RFC 7519, section 4.1.3](https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.3) and evaluates to true if at least one entry from the provided `audience`  arrays is present in the `aud` claim.
=> fix: `audience` assertion adheres to RFC-7519, section 4.1.3

docs/content/guides/proxies/contour.adoc, examples/kubernetes/Justfile, examples/kubernetes/contour/helm-values.yaml, examples/kubernetes/quickstarts/demo-app/overlays/contour-ingress/http-proxy.yaml
closes #1077
In addition to the docs, this PR updates the available examples to showcase both, global and route based integration.
=> docs: Contour integration guide updated to cover global configuration in addition to the route based one

README.md
According to [SLSA documentation](https://slsa.dev) and also answers from the SLSA comunity, this Project certifies for [SLSA Level 3](https://slsa.dev/get-started#slsa-3). There is currently only a self-assessment option possible. There are however plans to have project audits in the future which would officially certify the project.
=> chore: SLSA badge added

internal/handler/envoyextauth/grpcv3/request_context.go, internal/handler/requestcontext/mocks/context.go, internal/handler/requestcontext/request_context.go, internal/heimdall/context.go, internal/heimdall/mocks/context.go, internal/rules/mechanisms/finalizers/cookie_finalizer_test.go, internal/rules/mechanisms/finalizers/header_finalizer_test.go, internal/rules/mechanisms/finalizers/jwt_finalizer.go, internal/rules/mechanisms/finalizers/jwt_finalizer_test.go
fix for #1487.
Before it usage of the `dig` template function resulted in an internal error due to a type conversation issue.
=> chore: type for the `Outputs` removed and made it `map[string]any` to have better support in templates

internal/rules/mechanisms/authenticators/jwt_authenticator.go, internal/rules/mechanisms/authenticators/oauth2_introspection_authenticator.go, internal/rules/mechanisms/oauth2/expectation.go, internal/rules/mechanisms/oauth2/expectation_test.go
same as #1658 (but for the release branch, cherry pick from the referenced PR)
The verification of the claims is done using an `Expectation` object initially created from the `jwt` authenticator configuration. If the `metadata_endpoint` is used, a new `Expectation` object, based on the above said one, is created. The contents of that new object is a result of merging the properties from the initial object with data received from the OIDC discovery endpoint, where new data is only used in the resulting object if the old one didn't have them set. Unfortunately the implementation of the `Merge()` method, responsible for the creation of that new object was not idempotent. It updated the properties of the initial object during the merge. That way the subsequent `Expectation` objects had wrong …
=> fix: OAuth2 `iss` claim verification in JWT/OIDC authenticators when used with `metadata_endpoint`

osv-scanner.toml
[OSV Scanner](https://github.com/google/osv-scanner) is used by [scorecard](https://github.com/ossf/scorecard)
=> chore: OSV Scanner configuration added

internal/handler/middleware/grpc/otelmetrics/interceptor.go, internal/handler/middleware/grpc/otelmetrics/interceptor_test.go, internal/handler/middleware/http/otelmetrics/handler.go, internal/handler/middleware/http/otelmetrics/handler_test.go, internal/otel/resource.go, internal/x/opentelemetry/mocks/mock.go
OTEL has deprecated some of the attributes used so far in exposed metrics/traces. See also [HTTP semantic conventions declared stable](https://opentelemetry.io/blog/2023/http-conventions-declared-stable/) and [Network Deprecated Attributes](https://opentelemetry.io/docs/specs/semconv/attributes-registry/network/#network-deprecated-attributes)
This PR updates the code to 
* use semconv 1.26.0, 
* use `client.address` instead of the deprecated `net.peer.name`,
* use `client.port` instead of the deprecated `net.peer.port`,
* use `server.address` instead of the deprecated `net.host.name`,
* use `server.port` instead of the deprecated `net.host.port`,
* use `network.peer.address` instead of the deprecated `net.sock.peer.addr`,
* use `network.peer.port` instead of the deprecated …
=> refactor!: Deprecated OTEL attributes replaced

docs/content/guides/authn/_index.adoc, docs/content/guides/authn/oidc_first_party_auth.adoc
closes #1063 
This PR contains a new guide on how heimdall can be used with an OIDC provider, like e.g. Keycloak to implement first-party authentication.
=> docs: Guide for First-Party Authentication with OpenID Connect

DockerHub-README.md, docker/docker-compose.template.dbg, docs/content/docs/getting_started/protect_an_app.adoc, docs/content/guides/authn/oidc_first_party_auth.adoc, docs/content/guides/authz/openfga.adoc, docs/content/guides/proxies/traefik.adoc, examples/docker-compose/quickstarts/README.md, examples/docker-compose/quickstarts/docker-compose-envoy-grpc.yaml, examples/docker-compose/quickstarts/docker-compose-envoy-http.yaml, examples/docker-compose/quickstarts/docker-compose-proxy.yaml, examples/docker-compose/quickstarts/docker-compose-traefik.yaml, examples/docker-compose/quickstarts/docker-compose.yaml, examples/kubernetes/metallb/configure.sh
This PR introduces updates related to Docker Compose, such as replacing `docker-compose` with `docker compose` and removing the `version` property from the used `docker-compose.yaml` files, which has been deprecated by Docker.
=> chore: Docker compose related updates

go.sum, internal/handler/decision/service.go, internal/handler/management/service.go, internal/handler/proxy/service.go
closes #2048
If tracing is enabled, the OTEL Trace information (parent, trace and span ids) is logged again, making correlation of logs and traces possible again.
=> fix: Correlation of OTEL Traces and Logs

docs/content/guides/proxies/caddy.adoc, docs/content/guides/proxies/contour.adoc, docs/content/guides/proxies/emissary.adoc, docs/content/guides/proxies/envoy.adoc, docs/content/guides/proxies/envoy_gateway.adoc, docs/content/guides/proxies/haproxy.adoc, docs/content/guides/proxies/istio.adoc, docs/content/guides/proxies/nginx.adoc, docs/content/guides/proxies/traefik.adoc, examples/docker-compose/quickstarts/Caddyfile, examples/docker-compose/quickstarts/docker-compose-caddy.yaml
closes #1814 
This PR introduces a new integration guide on integrating heimdall with [Caddy](https://caddyserver.com/) and includes a Docker Compose-based setup for demonstration purposes.
=> docs: Caddy integration guide and demo examles

docs/content/docs/concepts/provider.adoc, docs/content/docs/concepts/rules.adoc, docs/content/docs/configuration/types.adoc, docs/content/docs/getting_started/protect_an_app.adoc, docs/content/docs/mechanisms/authorizers.adoc, docs/content/docs/mechanisms/contextualizers.adoc, docs/content/docs/mechanisms/error_handlers.adoc, docs/content/docs/mechanisms/evaluation_objects.adoc, docs/content/docs/mechanisms/finalizers.adoc, docs/content/docs/operations/cache.adoc, docs/content/docs/operations/configuration.adoc, docs/content/docs/operations/observability.adoc, docs/content/guides/authn/oidc_first_party_auth.adoc, docs/content/guides/authz/openfga.adoc, docs/content/guides/proxies/contour.adoc, docs/content/guides/proxies/envoy_gateway.adoc, docs/content/guides/proxies/istio.adoc, docs/content/guides/proxies/traefik.adoc
These are mostly spelling fixes. The following changes are also noteworthy:
- Change Docker org for "whoami" per deprecation notice at <https://hub.docker.com/r/containous/whoami/>
- `HEIMDALLCFG_SERVE_TRUSTED__PROXIES_0`: the same environmental variable name was defined twice, which doesn't make sense. I'm *assuming* the second one should be _1 but I didn't test it. Interestingly, this was `_0` even prior to a recent fix to this line that moved the escaped `_`, but the _0 was kept. But there is no way to configure the same environmental variable to two different values, so I assume it must be wrong!
My editor (vim) adds trailing newlines (which is typical in *nix). I noticed it was inconsistent whether or not the existing files had these or not, so I didn't make any special effort to …
=> chore: Improve spelling & grammar in docs

docs/content/docs/rules/regular_rule.adoc, internal/rules/repository_impl_test.go, internal/rules/route_matcher.go, internal/rules/route_matcher_test.go, internal/rules/rule_factory_impl.go
closes #2232
Prior to this PR, the implemented logic used an AND approach when evaluating host expressions. This PR improves the documentation as well by clearly describing how the different conditions are combined.
=> fix: Matching multiple hosts implements OR logic now

docs/content/docs/mechanisms/finalizers.adoc, internal/rules/mechanisms/finalizers/header_finalizer.go, internal/rules/mechanisms/finalizers/header_finalizer_test.go
Closes #2206 
This PR introduces support for multiple headers with the same name by allowing newline-separated values in the `header` finalizer. The values are split and added as individual headers, ensuring compatibility with applications that rely on this behavior.
=> feat(header-finalizer): support multiple headers with same name

docs/content/docs/getting_started/installation.adoc
=> docs: Extend installation section to include Heimdall installation via Nix package manager

.github/workflows/release.yaml, charts/heimdall/README.adoc, docs/content/docs/operations/security.adoc
closes #2291
This PR modifies the release workflow to publish the Helm Chart as an OCI image alongside its existing gh-pages distribution. It also implements signing of the chart image using Cosign and generates SLSA provenance for it.
=> feat: Helm Chart as OCI image

charts/heimdall/values.yaml, docs/content/docs/operations/cache.adoc, go.mod, go.sum, internal/cache/memory/cache.go, internal/cache/memory/cache_test.go, internal/cache/memory/config_decoder.go, schema/config.schema.json
closes #1250 
This PR limits the in-memory cache of heimdall by default to 128MB to prevent excessive memory consumption, and introduces optional configuration options to allow fine-tuning. The snippet below shows the new configuration options:
```yaml
cache:
type: in-memory
config: # <- this is new
memory_limit: 256MB # defaults to 128MB if not set
entry_limit: 10000 # unbound if not set
```
=> feat: Configurable limits for in-memory cache

charts/heimdall/README.adoc, charts/heimdall/templates/hpa.yaml, charts/heimdall/tests/deployment_test.yaml, charts/heimdall/tests/hpa_test.yaml, charts/heimdall/values.yaml, docs/content/docs/getting_started/installation.adoc, docs/content/docs/operations/cache.adoc, docs/content/docs/operations/security.adoc, docs/content/guides/proxies/istio.adoc
closes #2442
This PR addresses a usability and configuration issue with the Helm chart's default behavior. 
The chart enabled autoscaling by default but does not configure default resource requests, which led to silent failures in the HPA. The HPA would appear active, but pods would not scale, and errors like those shown in the referenced ticket were not visible unless actively checked.
To avoid misleading behavior, this PR introduced the following changes:
* Autoscaling is now disabled by default to avoid broken out-of-the-box behavior
* A conditional check has been added to the HPA template to ensure it only renders if resource requests required by a particular metric are explicitly defined and raises an error otherwise
* Chart README has been updated to document this behavior and guide …
=> fix: Helm Chart updated to disable autoscaling by default and to check resource request configuration in HPA template

docs/content/docs/operations/security.adoc
closes #2576 
This PR adds the missing documentation for the `--insecure-skip-all-tls-enforcement` flag.
=> docs: Added missing description for the `--insecure-skip-all-tls-enforcement` flag

cmd/validate/test_data/config-valid.yaml, cmd/validate/test_data/ruleset-valid.yaml, docs/content/docs/mechanisms/contextualizers.adoc, internal/config/test_data/test_config.yaml, internal/rules/mechanisms/contextualizers/map_contextualizer.go, internal/rules/mechanisms/contextualizers/map_contextualizer_test.go, schema/config.schema.json
relates to #2537
This PR introduces updates related to the work done in #2537:
* The JSON schema has been updated to define the new contextualizer. Without this change, the new functionality could not be used, as attempts to configure the `map` contextualizer would result in schema validation errors.
* The `continue_on_error` property has been removed, as errors raised by this contextualizer can only be related to misconfiguration, which should prevent the pipeline from continuing.
=> chore: `map` contextualizer update

examples/kubernetes/Justfile, examples/kubernetes/traefik/global-mw-helm-values.yaml, examples/kubernetes/traefik/helm-values.yaml
house keeping
Using the most recent version of traefik in kubernetes examples.
=> docs: traefik helm chart version used in kubernetes examples updated to v37.1.1
